---
# tasks file for ansible-role-git2u

- name: Include common variables
  include_vars: '{{ platform_vars }}'
  with_first_found:
    - "common-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "common-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  loop_control:
    loop_var: platform_vars
  tags: [ common ]

- name: Setup packages in platform-specific manner
  include_tasks: "{{ platform }}"
  with_first_found:
    - "setup-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "not-supported.yml"
  loop_control:
    loop_var: platform
  tags: [ install_packages ]
